server:
  port: 8086
  servlet:
    context-path: /auth


spring:

  profiles:
    active: product

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/AUTH_CENTER?charset=utf8mb4&serverTimezone=UTC&useSSL=false
    username: root
    password: cjh

  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: UTC

  redis:
    password: rootredis
    host: localhost
    port: 6379


  # 出现错误时，直接抛出异常
  mvc:
    throw-exception-if-no-handler-found: true
  # 不要为资源文件建立映射
  resources:
    add-mappings: false
